### ISSUE TITLE
Cannot use passed URI to set wallpaper; check that the type returned by ContentProvider matches image/*

### ISSUE THREAD

**Issue by MuhammadAkkad** [ganeshsp1/wallpaperplugin#1]
Hi 

I'm facing this error: 
`W/System.err(11376): java.lang.IllegalArgumentException: Cannot use passed URI to set wallpaper; check that the type returned by ContentProvider matches image/*
W/System.err(11376): 	at android.app.WallpaperManager.getCropAndSetWallpaperIntent(WallpaperManager.java:894)
W/System.err(11376): 	at com.ganeshsp.plugins.wallpaper.WallpaperPluginManager.setWallpaperWithCrop(WallpaperPluginManager.java:67)
W/System.err(11376): 	at com.ganeshsp.plugins.wallpaper.WallpaperPluginManager.onMethodCall(WallpaperPluginManager.java:42)
W/System.err(11376): 	at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:231)
W/System.err(11376): 	at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:93)
W/System.err(11376): 	at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:642)
W/System.err(11376): 	at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err(11376): 	at android.os.MessageQueue.next(MessageQueue.java:323)
W/System.err(11376): 	at android.os.Looper.loop(Looper.java:136)
W/System.err(11376): 	at android.app.ActivityThread.main(ActivityThread.java:6119)
W/System.err(11376): 	at java.lang.reflect.Method.invoke(Native Method)
W/System.err(11376): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
W/System.err(11376): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)`

My codes are basically the same of yours except permission handling because I've implemented it already

` ///This code helps in downloading a jpeg to local folder
  Future<String> _downloadFileUsingDio(String url, String _photoId) async {
    final Dio dio = Dio();
    final String dir = await _localPath;
    final String localFile = '$dir/$_photoId.jpg';
    final File file = File(localFile);
    if (!file.existsSync()) {
      try {
        await dio.download(
            url, localFile, onReceiveProgress: (int received, int total) {
          if (total != -1) {
            print('Photo downloading : ' +
                (received / total * 100).toStringAsFixed(0) +
                '%');
          }
        });
        return localFile;
      } catch (error) {
        print(error);
      }
    }
    return localFile;
  }

  ///returns the local path + /wallpapers, this is where the image file is downloaded.
  Future<String> get _localPath async {
    final Directory appDocDirectory = await getExternalStorageDirectory();
    final Directory directory =
    await Directory(appDocDirectory.path + '/wallpapers')
        .create(recursive: true);
    // The created directory is returned as a Future.
    return directory.path;
  }

  // Platform messages are asynchronous, so we initialize in an async method.
  Future<void> setWallCrop(_wallpaperImageUrl) async {
    String wallpaperStatus = 'Unexpected Result';
    final String _localFile = await _downloadFileUsingDio(
        _wallpaperImageUrl,
        'test_wallpaper');
    // Platform messages may fail, so we use a try/catch PlatformException.
    try {
      Wallpaperplugin.setWallpaperWithCrop(localFile: _localFile);
      wallpaperStatus = 'new Wallpaper set';
    } catch (e) {
      print('Platform exception $e');
      wallpaperStatus = 'Platform Error Occured';
    }
    if (!mounted)
      return;
    setState(() {
      _wallpaperStatus = wallpaperStatus;
    });
  }`

Flutter doctor:

`[√] Flutter (Channel stable, v1.12.13+hotfix.9, on Microsoft Windows [Version 10.0.18363.535], locale en-US)
    • Flutter version 1.12.13+hotfix.9 at C:\src\sdk\flutter
    • Framework revision f139b11009 (4 weeks ago), 2020-03-30 13:57:30 -0700
    • Engine revision af51afceb8
    • Dart version 2.7.2

[√] Android toolchain - develop for Android devices (Android SDK version 29.0.3)
    • Android SDK at C:/Users/09370755/AppData/Local/Android/Sdk
    • Android NDK location not configured (optional; useful for native profiling support)
    • Platform android-29, build-tools 29.0.3
    • ANDROID_HOME = C:/Users/09370755/AppData/Local/Android/Sdk
    • Java binary at: C:\Program Files\Android\Android Studio1\jre\bin\java
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)
    • All Android licenses accepted.

[√] Android Studio (version 3.6)
    • Android Studio at C:\Program Files\Android\Android Studio1
    • Flutter plugin version 45.1.1
    • Dart plugin version 192.7761
    • Java version OpenJDK Runtime Environment (build 1.8.0_212-release-1586-b04)

[√] IntelliJ IDEA Community Edition (version 2019.3)
    • IntelliJ at C:\Program Files\JetBrains\IntelliJ IDEA Community Edition 2019.3.3
    • Flutter plugin version 45.1.2
    • Dart plugin version 193.6911.31

[√] Connected device (1 available)
    • Android SDK built for x86 • emulator-5554 • android-x86 • Android 7.1.1 (API 25) (emulator)

• No issues found!`

SDK
`        minSdkVersion 24
        targetSdkVersion 29`

**Comment by tsvillain** [comment]
Facing the same issue on Android 10 Device.
`W/System.err( 8869): java.lang.IllegalArgumentException: Cannot use passed URI to set wallpaper; check that the type returned by ContentProvider matches image/*
W/System.err( 8869):    at android.app.WallpaperManager.getCropAndSetWallpaperIntent(WallpaperManager.java:1128)
W/System.err( 8869):    at com.ganeshsp.plugins.wallpaper.WallpaperPluginManager.setWallpaperWithCrop(WallpaperPluginManager.java:67)
W/System.err( 8869):    at com.ganeshsp.plugins.wallpaper.WallpaperPluginManager.onMethodCall(WallpaperPluginManager.java:42)
W/System.err( 8869):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:230)
W/System.err( 8869):    at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:85)
W/System.err( 8869):    at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:683)
W/System.err( 8869):    at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 8869):    at android.os.MessageQueue.next(MessageQueue.java:336)
W/System.err( 8869):    at android.os.Looper.loop(Looper.java:174)
W/System.err( 8869):    at android.app.ActivityThread.main(ActivityThread.java:7356)
W/System.err( 8869):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 8869):    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
W/System.err( 8869):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)`

**Comment by ganeshsp1** [comment]
This is a bug with android Oreo and I could find some workarounds in the below which will have to be implemented in the native code as a workaround
https://stackoverflow.com/questions/47254498/getcropandsetwallpaperintent-content-uri-error

**Comment by ganeshsp1** [comment]
I have tried out that fix as mentioned in stackoverflow as I don't have a device where it's facing this issue, please try it out and reopen the issue if it doesn't work
